# Generated by Django 3.2 on 2021-04-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_queue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='queue',
        ),
    ]
