# Generated by Django 3.2 on 2021-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
