# Generated by Django 3.2 on 2021-04-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_songs_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='lyrics',
        ),
    ]
