# Generated by Django 3.2 on 2021-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_songs_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='lang',
            field=models.CharField(default='english', max_length=10),
        ),
    ]
