# Generated by Django 3.2 on 2021-04-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210413_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='tags',
        ),
    ]
